// Training constants
export const TRAINING_EXERCISES_REPOSITORY = 'EXERCISES_REPOSITORY';
export const WORKOUT_SESSIONS_REPOSITORY = 'WORKOUT_SESSIONS_REPOSITORY';

// Body metrics constants
export const BODY_METRICS_REPOSITORY = 'BODY_METRICS_REPOSITORY';
export const BODY_PHOTOS_REPOSITORY = 'BODY_PHOTOS_REPOSITORY';

// Activity logs constants
export const ACTIVITY_LOGS_REPOSITORY = 'ACTIVITY_LOGS_REPOSITORY';
