export const EXERCISES_REPOSITORY = 'EXERCISES_REPOSITORY';
export const TRAINING_SESSIONS_REPOSITORY = 'TRAINING_SESSIONS_REPOSITORY';
export const BODY_METRICS_REPOSITORY = 'BODY_METRICS_REPOSITORY';
export const BODY_PHOTOS_REPOSITORY = 'BODY_PHOTOS_REPOSITORY';
export const ACTIVITY_LOGS_REPOSITORY = 'ACTIVITY_LOGS_REPOSITORY';
