import { DataSource } from 'typeorm';

const exercises = [
  // ─── CHEST ──────────────────────────────────────────────────
  {
    name: 'Hít đất (Push-up)',
    name_en: 'Push-up',
    description: 'Bài tập thể trọng kinh điển tăng sức mạnh ngực, vai và tay sau.',
    primaryMuscleGroup: 'chest',
    intensity: 'moderate',
    metValue: 3.8,
    instructions: '1. Nằm sấp, tay rộng bằng vai.\n2. Đẩy người lên thẳng tay.\n3. Hạ người xuống từ từ, ngực gần chạm sàn.\n4. Lặp lại.',
  },
  {
    name: 'Bench Press (Thanh đòn nằm)',
    name_en: 'Barbell Bench Press',
    description: 'Bài tập tạ cơ bản phát triển cơ ngực trên, tay trước và vai trước.',
    primaryMuscleGroup: 'chest',
    intensity: 'heavy',
    metValue: 5.0,
    instructions: '1. Nằm trên băng ghế, tay bắt thanh đòn rộng hơn vai.\n2. Hạ thanh xuống ngực.\n3. Đẩy lên hết tầm.',
  },
  {
    name: 'Dumbbell Fly (Tạ đôi dang ngang)',
    name_en: 'Dumbbell Fly',
    description: 'Bài tập cô lập cơ ngực bằng tạ đôi, giúp kéo giãn và tăng chiều rộng ngực.',
    primaryMuscleGroup: 'chest',
    intensity: 'moderate',
    metValue: 3.5,
    instructions: '1. Nằm trên băng ghế, tay cầm tạ đôi.\n2. Dang rộng hai tay theo cung.\n3. Khép lại vị trí ban đầu.',
  },
  // ─── BACK ────────────────────────────────────────────────────
  {
    name: 'Kéo xà đơn (Pull-up)',
    name_en: 'Pull-up',
    description: 'Bài tập thể trọng phát triển lưng rộng, tay trước và core.',
    primaryMuscleGroup: 'back',
    intensity: 'heavy',
    metValue: 4.0,
    instructions: '1. Treo người trên xà, tay rộng bằng vai.\n2. Kéo người lên đến khi cằm qua xà.\n3. Hạ từ từ.',
  },
  {
    name: 'Deadlift (Kéo đất)',
    name_en: 'Deadlift',
    description: 'Bài tập compound cơ bản nhất phát triển lưng, mông và chân sau.',
    primaryMuscleGroup: 'back',
    intensity: 'heavy',
    metValue: 6.0,
    instructions: '1. Đứng trước thanh đòn, bàn chân rộng bằng hông.\n2. Gập người, lưng thẳng, tay bắt thanh.\n3. Đứng thẳng người kéo thanh lên.\n4. Hạ xuống từ từ.',
  },
  {
    name: 'Bent-over Row (Rowing đứng)',
    name_en: 'Bent-over Barbell Row',
    description: 'Phát triển cơ lưng giữa và tay trước, tăng độ dày lưng.',
    primaryMuscleGroup: 'back',
    intensity: 'heavy',
    metValue: 5.0,
    instructions: '1. Gập người ~45°, lưng thẳng.\n2. Kéo thanh đòn lên bụng dưới.\n3. Hạ xuống từ từ.',
  },
  {
    name: 'Kéo lưng cáp cao (Lat Pulldown)',
    name_en: 'Lat Pulldown',
    description: 'Phát triển cơ lưng rộng, thích hợp cho người chưa kéo được xà.',
    primaryMuscleGroup: 'back',
    intensity: 'moderate',
    metValue: 3.5,
    instructions: '1. Ngồi ở máy kéo lưng, tay bắt thanh rộng hơn vai.\n2. Kéo thanh xuống ngang ngực trên.\n3. Hạ từ từ về vị trí ban đầu.',
  },
  // ─── LEGS ────────────────────────────────────────────────────
  {
    name: 'Squat (Ngồi xổm tạ)',
    name_en: 'Barbell Squat',
    description: 'Vua của các bài tập chân, phát triển đùi trước, mông và cơ thể toàn diện.',
    primaryMuscleGroup: 'legs',
    intensity: 'heavy',
    metValue: 6.0,
    instructions: '1. Đặt thanh đòn lên vai, chân rộng bằng vai.\n2. Hạ người xuống như ngồi ghế đến khi đùi song song sàn.\n3. Đứng thẳng lên.',
  },
  {
    name: 'Lunges (Bước dài)',
    name_en: 'Lunges',
    description: 'Tập đùi trước và mông đơn bên, cải thiện sự cân bằng.',
    primaryMuscleGroup: 'legs',
    intensity: 'moderate',
    metValue: 4.0,
    instructions: '1. Đứng thẳng, bước dài một chân về trước.\n2. Hạ đầu gối sau gần chạm sàn.\n3. Đứng dậy, đổi chân.',
  },
  {
    name: 'Leg Press (Máy ép chân)',
    name_en: 'Leg Press',
    description: 'Phát triển đùi trước và sau an toàn cho người mới.',
    primaryMuscleGroup: 'legs',
    intensity: 'moderate',
    metValue: 4.5,
    instructions: '1. Ngồi vào máy, đặt chân lên bàn đạp rộng bằng vai.\n2. Đẩy bàn đạp ra hết tầm.\n3. Hạ từ từ về góc 90°.',
  },
  {
    name: 'Romanian Deadlift (Kéo đất chân thẳng)',
    name_en: 'Romanian Deadlift',
    description: 'Phát triển cơ đùi sau và mông, cải thiện linh hoạt.',
    primaryMuscleGroup: 'legs',
    intensity: 'moderate',
    metValue: 5.0,
    instructions: '1. Đứng thẳng, tay cầm thanh đòn.\n2. Gập người, hạ thanh xuống theo chân, đầu gối hơi gập.\n3. Đứng thẳng lại.',
  },
  // ─── SHOULDERS ───────────────────────────────────────────────
  {
    name: 'Overhead Press (Đẩy đầu)',
    name_en: 'Overhead Press',
    description: 'Phát triển toàn bộ cơ vai, đặc biệt phần trước và giữa.',
    primaryMuscleGroup: 'shoulders',
    intensity: 'heavy',
    metValue: 4.5,
    instructions: '1. Đứng thẳng hoặc ngồi, tay cầm thanh ngang vai.\n2. Đẩy thẳng lên đầu.\n3. Hạ xuống từ từ.',
  },
  {
    name: 'Lateral Raise (Dang tạ ngang)',
    name_en: 'Dumbbell Lateral Raise',
    description: 'Cô lập cơ vai giữa, tạo độ rộng vai.',
    primaryMuscleGroup: 'shoulders',
    intensity: 'light',
    metValue: 3.0,
    instructions: '1. Đứng thẳng, tay cầm tạ đôi.\n2. Dang hai tay lên ngang vai.\n3. Hạ từ từ.',
  },
  // ─── ARMS ────────────────────────────────────────────────────
  {
    name: 'Bicep Curl (Cuộn tay trước)',
    name_en: 'Dumbbell Bicep Curl',
    description: 'Cô lập cơ tay trước, tăng khối lượng và sức mạnh tay.',
    primaryMuscleGroup: 'arms',
    intensity: 'light',
    metValue: 3.0,
    instructions: '1. Đứng thẳng, tay cầm tạ đôi, khuỷu tay sát hông.\n2. Gập tay lên đến vai.\n3. Hạ từ từ.',
  },
  {
    name: 'Tricep Dips (Chống tay ghế)',
    name_en: 'Tricep Dips',
    description: 'Phát triển cơ tay sau, có thể tập với trọng lượng cơ thể.',
    primaryMuscleGroup: 'arms',
    intensity: 'moderate',
    metValue: 3.5,
    instructions: '1. Ngồi mép ghế, tay chống cạnh hông.\n2. Trượt người ra khỏi ghế, hạ người xuống.\n3. Đẩy lên hết tầm.',
  },
  // ─── CORE ────────────────────────────────────────────────────
  {
    name: 'Plank (Chống đẩy tĩnh)',
    name_en: 'Plank',
    description: 'Tăng cường sức mạnh core toàn diện và sự ổn định của cột sống.',
    primaryMuscleGroup: 'core',
    intensity: 'moderate',
    metValue: 3.5,
    instructions: '1. Nằm sấp, chống bằng khuỷu tay và mũi chân.\n2. Giữ người thẳng như tấm ván.\n3. Duy trì trong thời gian yêu cầu.',
  },
  {
    name: 'Crunch (Gập bụng)',
    name_en: 'Crunch',
    description: 'Cô lập cơ bụng trên, bài tập cơ bản nhất cho bụng 6 múi.',
    primaryMuscleGroup: 'core',
    intensity: 'light',
    metValue: 2.8,
    instructions: '1. Nằm ngửa, gối gập, tay sau đầu.\n2. Gập người lên bằng cơ bụng (không dùng cổ).\n3. Hạ từ từ.',
  },
  {
    name: 'Russian Twist',
    name_en: 'Russian Twist',
    description: 'Phát triển cơ bụng nghiêng, giúp thu gọn eo.',
    primaryMuscleGroup: 'core',
    intensity: 'moderate',
    metValue: 3.0,
    instructions: '1. Ngồi với lưng nghiêng ~45°, chân nâng.\n2. Xoay người sang hai bên, tay chạm sàn mỗi phía.\n3. Có thể cầm tạ để tăng độ khó.',
  },
  {
    name: 'Leg Raise (Nâng chân)',
    name_en: 'Hanging Leg Raise',
    description: 'Tăng cường cơ bụng dưới và flexor hông.',
    primaryMuscleGroup: 'core',
    intensity: 'moderate',
    metValue: 3.2,
    instructions: '1. Treo người trên xà.\n2. Nâng chân thẳng lên ngang hông hoặc cao hơn.\n3. Hạ từ từ.',
  },
  // ─── CARDIO ──────────────────────────────────────────────────
  {
    name: 'Chạy bộ',
    name_en: 'Running',
    description: 'Cardio hiệu quả nhất, đốt calories cao và cải thiện sức bền tim mạch.',
    primaryMuscleGroup: 'cardio',
    intensity: 'moderate',
    metValue: 8.0,
    instructions: '1. Khởi động nhẹ 5 phút.\n2. Chạy ở tốc độ vừa phải.\n3. Hạ nhiệt 5 phút cuối.',
  },
  {
    name: 'Đạp xe',
    name_en: 'Cycling',
    description: 'Cardio ít tác động lên khớp, phù hợp mọi lứa tuổi.',
    primaryMuscleGroup: 'cardio',
    intensity: 'moderate',
    metValue: 7.5,
    instructions: '1. Điều chỉnh yên xe phù hợp chiều cao.\n2. Đạp ở tốc độ vừa phải.\n3. Duy trì nhịp thở đều.',
  },
  {
    name: 'Nhảy dây',
    name_en: 'Jump Rope',
    description: 'Cardio cường độ cao đốt nhiều calories trong thời gian ngắn.',
    primaryMuscleGroup: 'cardio',
    intensity: 'heavy',
    metValue: 10.0,
    instructions: '1. Cầm dây hai tay, xoay bằng cổ tay.\n2. Nhảy qua dây mỗi vòng.\n3. Bắt đầu 30 giây, tăng dần.',
  },
  {
    name: 'Bơi lội',
    name_en: 'Swimming',
    description: 'Tập cardio toàn thân, không tác động khớp, phù hợp người chấn thương.',
    primaryMuscleGroup: 'cardio',
    intensity: 'moderate',
    metValue: 7.0,
    instructions: '1. Khởi động ngoài hồ.\n2. Bơi liên tục theo đường thẳng.\n3. Chú ý kỹ thuật thở.',
  },
  {
    name: 'Đi bộ nhanh',
    name_en: 'Brisk Walking',
    description: 'Cardio nhẹ phù hợp người mới bắt đầu hoặc hồi phục.',
    primaryMuscleGroup: 'cardio',
    intensity: 'light',
    metValue: 3.5,
    instructions: '1. Đi ở tốc độ 5-6 km/h.\n2. Giữ lưng thẳng, tay đánh nhịp nhàng.\n3. Mục tiêu 30 phút/ngày.',
  },
  // ─── FULL_BODY ───────────────────────────────────────────────
  {
    name: 'Burpee',
    name_en: 'Burpee',
    description: 'Bài tập toàn thân cường độ cao, đốt calories tối đa.',
    primaryMuscleGroup: 'full_body',
    intensity: 'heavy',
    metValue: 8.0,
    instructions: '1. Đứng thẳng.\n2. Ngồi xổm, đặt tay xuống sàn.\n3. Bật chân ra tư thế chống đẩy.\n4. Thực hiện 1 hít đất.\n5. Bật chân về, nhảy lên cao với tay qua đầu.',
  },
  {
    name: 'Mountain Climber',
    name_en: 'Mountain Climber',
    description: 'Kết hợp core và cardio, tăng nhịp tim nhanh.',
    primaryMuscleGroup: 'full_body',
    intensity: 'heavy',
    metValue: 8.0,
    instructions: '1. Vào tư thế chống đẩy cao.\n2. Gập gối kéo chân lên ngực luân phiên thật nhanh.\n3. Giữ hông không nhấp nhô.',
  },
  {
    name: 'Kettlebell Swing',
    name_en: 'Kettlebell Swing',
    description: 'Phát triển cơ sau người (posterior chain) và cardio hiệu quả.',
    primaryMuscleGroup: 'full_body',
    intensity: 'moderate',
    metValue: 6.0,
    instructions: '1. Đứng chân rộng hơn vai, tay cầm kettlebell.\n2. Gập hông đưa kettlebell ra sau giữa hai chân.\n3. Đẩy hông về trước, vung kettlebell lên ngang vai.',
  },
];

export async function seedExercises(dataSource: DataSource): Promise<void> {
  const repo = dataSource.getRepository('exercises');
  const existing = await repo.count();
  if (existing > 0) {
    console.log(`[Seed] exercises table already has ${existing} records. Skipping.`);
    return;
  }

  await repo.save(exercises);
  console.log(`[Seed] Inserted ${exercises.length} exercises.`);
}
