export const EXERCISES_REPOSITORY = 'EXERCISES_REPOSITORY';
export const WORKOUT_SESSIONS_REPOSITORY = 'WORKOUT_SESSIONS_REPOSITORY';
export const TRAINING_GOALS_REPOSITORY = 'TRAINING_GOALS_REPOSITORY';
